let nome="José da Sila";
let idade=27;
let peso=83.5;
let altura=1.7;
let plano=true;
let calcImc=peso/(altura*altura);
console.log(nome, "tem", idade, "anos", "e seu índice de massa corporal é de", calcImc.toFixed(1));
nome="Carlos de Souza";
idade=28;
peso=80.1;
altura=1.76;
calcImc=peso/(altura*altura);
console.log(nome, "tem", idade, "anos", "e seu índice de massa corporal é de", calcImc.toFixed(1)); 
nome="Aline Ferreira";
idade=33;
peso=63.7;
altura=1.53;
calcImc=peso/(altura*altura);
console.log(nome, "tem", idade, "anos", "e seu índice de massa corporal é de", calcImc.toFixed(1));
nome="Ana Paula";
idade=26;
peso=55;
altura=1.62;
calcImc=peso/(altura*altura);
console.log(nome, "tem", idade, "anos", "e seu índice de massa corporal é de", calcImc.toFixed(1));     